title: <p align="center"> Siti Nur Dzakiyyah </p>

logo: "/images/FotoFormal.png"

description:
  <p align="center">
  <a href="pdf/CVATS.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/siti-nur-dzakiyyah-7a748826a/">LinkedIn</a> |
  <a href="https://github.com/zakkyahh">GitHub</a>
  </p>
  
  <p align="justify">
  I am a statistic students at Diponegoro University
  <br><br>
  I am currently a Machine Learning Research Intern at Skim AI Technologies with a focus on NLP and Deep Learning research.
  <br><br>
  </p>
  
theme: jekyll-theme-minimal
google_analytics: UA-145578661-1 # Google Analytics tracking ID
