title: <p align="center"> Siti Nur Dzakiyyah </p>

logo: "/images/fotoformal.png"

description:
  <p align="center">
  <a href="pdf/CVATS.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/siti-nur-dzakiyyah-7a748826a/">LinkedIn</a> |
  <a href="https://github.com/zakkyahh">GitHub</a>
  </p>
  
  <p align="justify">
  A Statistic Student of Faculty of Science and Mathematics at Diponegoro Unisersity who has an enthusiasm for the world of data.
  <br><br>
  Has some experience in organization and committee. I am eager to find opportunities and learn new things.

  <br><br>
  </p>
  
theme: jekyll-theme-minimal
google_analytics: UA-145578661-1 # Google Analytics tracking ID
